name: Build modified antora UI dev

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm install -g gulp-cli
        npm install

    - name: Bundle UI
      run: |
        gulp bundle
        mv build/ui-bundle.zip build/ui-bundle-dev.zip

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        commit: ${{ github.ref_name }}
        generateReleaseNotes: true
        artifacts: "build/ui-bundle-dev.zip"
        makeLatest: false
