name: Build modified antora UI

on:
  push:
    branches:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: self-hosted-small
    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm install -g gulp-cli
        npm install

    - name: Bundle UI
      run: |
        gulp bundle

    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        artifacts: "build/ui-bundle.zip"
        makeLatest: true
